export const mockRisks = [
  {
    id: 1,
    title: "Unencrypted user data in transit",
    category: "Security",
    status: "Open",
    priority: "High",
    score: 85,
    owner: "Alice Johnson",
    createdDate: "2026-04-01",
  },
  {
    id: 2,
    title: "AI model hallucination in reports",
    category: "AI Risk",
    status: "In Progress",
    priority: "Medium",
    score: 62,
    owner: "Bob Smith",
    createdDate: "2026-04-05",
  },
  {
    id: 3,
    title: "No audit log for admin actions",
    category: "Compliance",
    status: "Open",
    priority: "High",
    score: 78,
    owner: "Carol White",
    createdDate: "2026-04-08",
  },
  {
    id: 4,
    title: "Third-party API has no SLA",
    category: "Operational",
    status: "Resolved",
    priority: "Low",
    score: 30,
    owner: "David Lee",
    createdDate: "2026-04-10",
  },
  {
    id: 5,
    title: "Missing input validation on forms",
    category: "Security",
    status: "In Progress",
    priority: "Medium",
    score: 55,
    owner: "Eva Green",
    createdDate: "2026-04-12",
  },
];
export const mockStats = {
  totalRisks: 5,
  openRisks: 2,
  inProgressRisks: 2,
  resolvedRisks: 1,
  highPriority: 2,
  mediumPriority: 2,
  lowPriority: 1,
  averageScore: 62,
  byCategory: [
    { category: "Security", count: 2 },
    { category: "AI Risk", count: 1 },
    { category: "Compliance", count: 1 },
    { category: "Operational", count: 1 },
    { category: "Financial", count: 0 },
    { category: "Reputational", count: 0 },
  ],
  byStatus: [
    { status: "Open", count: 2 },
    { status: "In Progress", count: 2 },
    { status: "Resolved", count: 1 },
  ],
  byPriority: [
    { priority: "High", count: 2 },
    { priority: "Medium", count: 2 },
    { priority: "Low", count: 1 },
  ],
  recentTrend: [
    { month: "Nov", count: 1 },
    { month: "Dec", count: 2 },
    { month: "Jan", count: 3 },
    { month: "Feb", count: 2 },
    { month: "Mar", count: 4 },
    { month: "Apr", count: 5 },
  ],
};